function names = controllerNames()
% CONTROLLERNAMES  The 27 boiler controller class names, in the C++ sim order.
names = {'PID','LQR','LQG','MPC','SMC','ESC','ADRC','LeadLagPID', ...
         'SmithPredictor','GPCRLS','EKFLQR','UKFLQR','FuzzyPID','FuzzySupMPC', ...
         'SupervisoryStack','AdditiveStack','WeightedStack','RepetitiveCtrl', ...
         'MRAC','Hinf','AdaptiveSP','NMPC','FL','MHELQR','LPVGS', ...
         'SubspaceIDLQG','AutoGS'};
end
