var searchData=
[
  ['h_20atomicparambuffer_20h_20a_0',['&lt;tt&gt;AtomicParamBuffer&lt;Params&gt;&lt;/tt&gt; (&lt;a href=&quot;lib/AtomicParamBuffer.h&quot; &gt;AtomicParamBuffer.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md101',1,'']]],
  ['h_20controllerstack_20h_20a_1',['&lt;tt&gt;ControllerStack&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerStack.h&quot; &gt;ControllerStack.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md94',1,'']]],
  ['h_20controllertraits_20h_20a_2',['&lt;tt&gt;ControllerTraits&lt;C&gt;&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerTraits.h&quot; &gt;ControllerTraits.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md91',1,'']]],
  ['h_20controllertuner_20h_20a_3',['&lt;tt&gt;RelayAutoTuner&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerTuner.h&quot; &gt;ControllerTuner.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md85',1,'']]],
  ['h_20discreteadrc_20h_20a_4',['&lt;tt&gt;DiscreteADRC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteADRC.h&quot; &gt;DiscreteADRC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md69',1,'']]],
  ['h_20discreteleadlag_20h_20a_5',['&lt;tt&gt;DiscreteLeadLag&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLeadLag.h&quot; &gt;DiscreteLeadLag.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md70',1,'']]],
  ['h_20discretelqg_20h_20a_6',['&lt;tt&gt;DiscreteLQG&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLQG.h&quot; &gt;DiscreteLQG.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md67',1,'']]],
  ['h_20discretelqr_20h_20a_7',['&lt;tt&gt;DiscreteLQR&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLQR.h&quot; &gt;DiscreteLQR.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md65',1,'']]],
  ['h_20discretempc_20h_20a_8',['&lt;tt&gt;DiscreteMPC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteMPC.h&quot; &gt;DiscreteMPC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md66',1,'']]],
  ['h_20discretepid_20h_20a_9',['&lt;tt&gt;DiscretePID&lt;/tt&gt; (&lt;a href=&quot;lib/DiscretePID.h&quot; &gt;DiscretePID.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md64',1,'']]],
  ['h_20discretesmc_20h_20a_10',['&lt;tt&gt;DiscreteSMC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteSMC.h&quot; &gt;DiscreteSMC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md68',1,'']]],
  ['h_20extremumseeker_20h_20a_11',['&lt;tt&gt;ExtremumSeeker&lt;/tt&gt; (&lt;a href=&quot;lib/ExtremumSeeker.h&quot; &gt;ExtremumSeeker.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md72',1,'']]],
  ['h_20fuzzylogic_20h_20a_12',['Fuzzy Logic Module (&lt;a href=&quot;lib/FuzzyLogic.h&quot; &gt;FuzzyLogic.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md73',1,'']]],
  ['h_20icontroller_20h_20a_13',['&lt;tt&gt;IController&lt;/tt&gt; (&lt;a href=&quot;lib/IController.h&quot; &gt;IController.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md61',1,'']]],
  ['h_20kalmanfilter_20h_20a_14',['&lt;tt&gt;KalmanFilter&lt;/tt&gt; (&lt;a href=&quot;lib/KalmanFilter.h&quot; &gt;KalmanFilter.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md82',1,'']]],
  ['h_20lib_20hal_20hal_20h_20a_15',['HAL (&lt;a href=&quot;lib/hal/HAL.h&quot; &gt;lib/hal/HAL.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md102',1,'']]],
  ['h_20metricsanalyzer_20h_20a_16',['&lt;tt&gt;MetricsAnalyzer&lt;/tt&gt; (&lt;a href=&quot;lib/MetricsAnalyzer.h&quot; &gt;MetricsAnalyzer.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md97',1,'']]],
  ['h_20plantmodel_20h_20a_17',['5.1 Core Types (&lt;a href=&quot;lib/PlantModel.h&quot; &gt;PlantModel.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md56',1,'']]],
  ['h_20smithpredictor_20h_20a_18',['&lt;tt&gt;SmithPredictor&lt;/tt&gt; (&lt;a href=&quot;lib/SmithPredictor.h&quot; &gt;SmithPredictor.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md71',1,'']]],
  ['h_20systemanalysis_20h_20a_19',['&lt;tt&gt;SystemAnalysis&lt;/tt&gt; (&lt;a href=&quot;lib/SystemAnalysis.h&quot; &gt;SystemAnalysis.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md98',1,'']]],
  ['h_20tunersuite_20h_20a_20',['&lt;tt&gt;TunerSuite&lt;/tt&gt; (&lt;a href=&quot;lib/TunerSuite.h&quot; &gt;TunerSuite.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md90',1,'']]],
  ['hal_21',['5.7 Real-Time Utilities &amp; HAL',['../md_docs_2DOCUMENTATION.html#autotoc_md100',1,'']]],
  ['hal_20a_20href_20lib_20hal_20hal_20h_20lib_20hal_20hal_20h_20a_22',['HAL (&lt;a href=&quot;lib/hal/HAL.h&quot; &gt;lib/hal/HAL.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md102',1,'']]],
  ['hal_20hal_20h_20lib_20hal_20hal_20h_20a_23',['HAL (&lt;a href=&quot;lib/hal/HAL.h&quot; &gt;lib/hal/HAL.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md102',1,'']]],
  ['hal_2eh_24',['HAL.h',['../HAL_8h.html',1,'']]],
  ['hasobserver_25',['hasObserver',['../classctrl_1_1IController.html#a465690c69f9da6a0dffffbe6d50808fb',1,'ctrl::IController']]],
  ['haspoleindomain_26',['hasPoleInDomain',['../classctrl_1_1PadeApproximator.html#ae3ec858ffcd1f787477b850c567886c8',1,'ctrl::PadeApproximator']]],
  ['hi_27',['hi',['../structctrl_1_1LinguisticVariable.html#a8a503d9327a29868472b6255261b0f16',1,'ctrl::LinguisticVariable']]],
  ['hinfparams_28',['HinfParams',['../structctrl_1_1HinfParams.html',1,'ctrl']]],
  ['hinfresult_29',['HinfResult',['../structctrl_1_1HinfResult.html',1,'ctrl']]],
  ['hpfcutoff_30',['hpfCutoff',['../structctrl_1_1ExtremumSeekerParams.html#a0e63643674a1200a5aaf487875588d63',1,'ctrl::ExtremumSeekerParams']]],
  ['href_20lib_20atomicparambuffer_20h_20atomicparambuffer_20h_20a_31',['&lt;tt&gt;AtomicParamBuffer&lt;Params&gt;&lt;/tt&gt; (&lt;a href=&quot;lib/AtomicParamBuffer.h&quot; &gt;AtomicParamBuffer.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md101',1,'']]],
  ['href_20lib_20controllerstack_20h_20controllerstack_20h_20a_32',['&lt;tt&gt;ControllerStack&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerStack.h&quot; &gt;ControllerStack.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md94',1,'']]],
  ['href_20lib_20controllertraits_20h_20controllertraits_20h_20a_33',['&lt;tt&gt;ControllerTraits&lt;C&gt;&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerTraits.h&quot; &gt;ControllerTraits.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md91',1,'']]],
  ['href_20lib_20controllertuner_20h_20controllertuner_20h_20a_34',['&lt;tt&gt;RelayAutoTuner&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerTuner.h&quot; &gt;ControllerTuner.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md85',1,'']]],
  ['href_20lib_20discreteadrc_20h_20discreteadrc_20h_20a_35',['&lt;tt&gt;DiscreteADRC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteADRC.h&quot; &gt;DiscreteADRC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md69',1,'']]],
  ['href_20lib_20discreteleadlag_20h_20discreteleadlag_20h_20a_36',['&lt;tt&gt;DiscreteLeadLag&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLeadLag.h&quot; &gt;DiscreteLeadLag.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md70',1,'']]],
  ['href_20lib_20discretelqg_20h_20discretelqg_20h_20a_37',['&lt;tt&gt;DiscreteLQG&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLQG.h&quot; &gt;DiscreteLQG.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md67',1,'']]],
  ['href_20lib_20discretelqr_20h_20discretelqr_20h_20a_38',['&lt;tt&gt;DiscreteLQR&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLQR.h&quot; &gt;DiscreteLQR.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md65',1,'']]],
  ['href_20lib_20discretempc_20h_20discretempc_20h_20a_39',['&lt;tt&gt;DiscreteMPC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteMPC.h&quot; &gt;DiscreteMPC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md66',1,'']]],
  ['href_20lib_20discretepid_20h_20discretepid_20h_20a_40',['&lt;tt&gt;DiscretePID&lt;/tt&gt; (&lt;a href=&quot;lib/DiscretePID.h&quot; &gt;DiscretePID.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md64',1,'']]],
  ['href_20lib_20discretesmc_20h_20discretesmc_20h_20a_41',['&lt;tt&gt;DiscreteSMC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteSMC.h&quot; &gt;DiscreteSMC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md68',1,'']]],
  ['href_20lib_20extremumseeker_20h_20extremumseeker_20h_20a_42',['&lt;tt&gt;ExtremumSeeker&lt;/tt&gt; (&lt;a href=&quot;lib/ExtremumSeeker.h&quot; &gt;ExtremumSeeker.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md72',1,'']]],
  ['href_20lib_20fuzzylogic_20h_20fuzzylogic_20h_20a_43',['Fuzzy Logic Module (&lt;a href=&quot;lib/FuzzyLogic.h&quot; &gt;FuzzyLogic.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md73',1,'']]],
  ['href_20lib_20hal_20hal_20h_20lib_20hal_20hal_20h_20a_44',['HAL (&lt;a href=&quot;lib/hal/HAL.h&quot; &gt;lib/hal/HAL.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md102',1,'']]],
  ['href_20lib_20icontroller_20h_20icontroller_20h_20a_45',['&lt;tt&gt;IController&lt;/tt&gt; (&lt;a href=&quot;lib/IController.h&quot; &gt;IController.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md61',1,'']]],
  ['href_20lib_20kalmanfilter_20h_20kalmanfilter_20h_20a_46',['&lt;tt&gt;KalmanFilter&lt;/tt&gt; (&lt;a href=&quot;lib/KalmanFilter.h&quot; &gt;KalmanFilter.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md82',1,'']]],
  ['href_20lib_20metricsanalyzer_20h_20metricsanalyzer_20h_20a_47',['&lt;tt&gt;MetricsAnalyzer&lt;/tt&gt; (&lt;a href=&quot;lib/MetricsAnalyzer.h&quot; &gt;MetricsAnalyzer.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md97',1,'']]],
  ['href_20lib_20plantmodel_20h_20plantmodel_20h_20a_48',['5.1 Core Types (&lt;a href=&quot;lib/PlantModel.h&quot; &gt;PlantModel.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md56',1,'']]],
  ['href_20lib_20smithpredictor_20h_20smithpredictor_20h_20a_49',['&lt;tt&gt;SmithPredictor&lt;/tt&gt; (&lt;a href=&quot;lib/SmithPredictor.h&quot; &gt;SmithPredictor.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md71',1,'']]],
  ['href_20lib_20systemanalysis_20h_20systemanalysis_20h_20a_50',['&lt;tt&gt;SystemAnalysis&lt;/tt&gt; (&lt;a href=&quot;lib/SystemAnalysis.h&quot; &gt;SystemAnalysis.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md98',1,'']]],
  ['href_20lib_20tunersuite_20h_20tunersuite_20h_20a_51',['&lt;tt&gt;TunerSuite&lt;/tt&gt; (&lt;a href=&quot;lib/TunerSuite.h&quot; &gt;TunerSuite.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md90',1,'']]],
  ['hysteresis_52',['hysteresis',['../structctrl_1_1RelayTunerConfig.html#a55f1bb1c0100e0c089bf1191b180e280',1,'ctrl::RelayTunerConfig']]],
  ['hysteresis_5frel_53',['hysteresis_rel',['../structctrl_1_1RelayTunerConfig.html#a8ee1199d4e0e1b07e7ea978df78576df',1,'ctrl::RelayTunerConfig']]]
];
