var searchData=
[
  ['3_201_20library_20tt_20lib_20tt_0',['3.1 Library (&lt;tt&gt;lib/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md44',1,'']]],
  ['3_202_20examples_20tt_20examples_20tt_1',['3.2 Examples (&lt;tt&gt;examples/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md45',1,'']]],
  ['3_203_20case_20studies_20tt_20case_20study_20tt_2',['3.3 Case Studies (&lt;tt&gt;case-study/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md46',1,'']]],
  ['3_204_20tests_20tt_20tests_20tt_3',['3.4 Tests (&lt;tt&gt;tests/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md50',1,'']]],
  ['3_205_20scripts_20tt_20scripts_20tt_4',['3.5 Scripts (&lt;tt&gt;scripts/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md51',1,'']]],
  ['3_206_20cheatsheets_20tt_20cheatsheet_20tt_5',['3.6 Cheatsheets (&lt;tt&gt;cheatsheet/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md52',1,'']]],
  ['3_20estimators_20identification_6',['5.3 Estimators &amp; Identification',['../md_docs_2DOCUMENTATION.html#autotoc_md95',1,'']]],
  ['3_20linking_20against_20the_20library_7',['2.3 Linking Against the Library',['../md_docs_2DOCUMENTATION.html#autotoc_md39',1,'']]],
  ['3_20lqr_20kalman_20lqg_20output_20feedback_8',['4.3 LQR + Kalman = LQG (Output Feedback)',['../md_docs_2DOCUMENTATION.html#autotoc_md57',1,'']]],
  ['3_20project_20structure_9',['3. Project Structure',['../md_docs_2DOCUMENTATION.html#autotoc_md43',1,'']]],
  ['3_20repository_20layout_20top_20level_10',['1.3 Repository Layout (Top Level)',['../md_docs_2DOCUMENTATION.html#autotoc_md34',1,'']]],
  ['3_20troubleshooting_11',['3. Troubleshooting',['../md_docs_2DEPLOYMENT.html#autotoc_md195',1,'']]],
  ['31–34_12',['5.8 Data-Driven &amp; ML Controllers (Parts 31–34)',['../md_docs_2DOCUMENTATION.html#autotoc_md141',1,'']]],
  ['31_20em_13',['31 em',['../md_docs_2DOCUMENTATION.html#autotoc_md146',1,'&lt;tt&gt;CBFSafetyFilter&lt;/tt&gt; (&lt;a href=&quot;lib/CBFSafetyFilter.h&quot; &gt;CBFSafetyFilter.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md150',1,'&lt;tt&gt;CEMController&lt;/tt&gt; (&lt;a href=&quot;lib/CEMController.h&quot; &gt;CEMController.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md148',1,'&lt;tt&gt;EchoStateNetwork&lt;/tt&gt; (&lt;a href=&quot;lib/EchoStateNetwork.h&quot; &gt;EchoStateNetwork.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md147',1,'&lt;tt&gt;GaussianProcess&lt;/tt&gt; (&lt;a href=&quot;lib/GaussianProcess.h&quot; &gt;GaussianProcess.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md142',1,'&lt;tt&gt;ILCController&lt;/tt&gt; (&lt;a href=&quot;lib/IterativeLearningControl.h&quot; &gt;IterativeLearningControl.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md144',1,'&lt;tt&gt;KoopmanEDMD&lt;/tt&gt; (&lt;a href=&quot;lib/KoopmanEDMD.h&quot; &gt;KoopmanEDMD.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md145',1,'&lt;tt&gt;L1AdaptiveController&lt;/tt&gt; (&lt;a href=&quot;lib/L1AdaptiveController.h&quot; &gt;L1AdaptiveController.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md149',1,'&lt;tt&gt;NeuralPID&lt;/tt&gt; (&lt;a href=&quot;lib/NeuralPID.h&quot; &gt;NeuralPID.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md143',1,'&lt;tt&gt;SINDy&lt;/tt&gt; + &lt;tt&gt;SINDyModel&lt;/tt&gt; (&lt;a href=&quot;lib/SINDy.h&quot; &gt;SINDy.h&lt;/a&gt;) &lt;em&gt;Part 31&lt;/em&gt;']]],
  ['33_20em_14',['33 em',['../md_docs_2DOCUMENTATION.html#autotoc_md154',1,'&lt;tt&gt;ControllerRegistry&lt;/tt&gt; + &lt;tt&gt;ControllerMonitor&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerRegistry.h&quot; &gt;ControllerRegistry.h&lt;/a&gt;, &lt;a href=&quot;lib/ControllerMonitor.h&quot; &gt;ControllerMonitor.h&lt;/a&gt;) &lt;em&gt;Part 33&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md151',1,'&lt;tt&gt;DynaController&lt;/tt&gt; (&lt;a href=&quot;lib/DynaController.h&quot; &gt;DynaController.h&lt;/a&gt;) &lt;em&gt;Part 33&lt;/em&gt;'],['../md_docs_2DOCUMENTATION.html#autotoc_md152',1,'&lt;tt&gt;ScenarioMPC&lt;/tt&gt; (&lt;a href=&quot;lib/ScenarioMPC.h&quot; &gt;ScenarioMPC.h&lt;/a&gt;) &lt;em&gt;Part 33&lt;/em&gt;']]],
  ['33_20header_20only_20em_15',['&lt;tt&gt;BayesianOptimizer&lt;/tt&gt; (&lt;a href=&quot;lib/BayesianOptimizer.h&quot; &gt;BayesianOptimizer.h&lt;/a&gt;) &lt;em&gt;Part 33, header-only&lt;/em&gt;',['../md_docs_2DOCUMENTATION.html#autotoc_md153',1,'']]],
  ['34_20header_20only_20em_16',['&lt;tt&gt;ComputationalDelayWrapper&lt;/tt&gt; (&lt;a href=&quot;lib/ComputationalDelayWrapper.h&quot; &gt;ComputationalDelayWrapper.h&lt;/a&gt;) &lt;em&gt;Part 34, header-only&lt;/em&gt;',['../md_docs_2DOCUMENTATION.html#autotoc_md155',1,'']]]
];
