var searchData=
[
  ['labels_0',['labels',['../structctrl_1_1ClusterResult.html#af8aa5fabeb52279b12ad87b489ef1476',1,'ctrl::ClusterResult']]],
  ['lastconverged_1',['lastConverged',['../classctrl_1_1MovingHorizonEstimator.html#a88b4ccb7af8e2d8853697b133b77fc3f',1,'ctrl::MovingHorizonEstimator']]],
  ['lastoutput_2',['lastoutput',['../classctrl_1_1IActuator.html#ad9c35118fbf95b959c85c65296b014ec',1,'ctrl::IActuator::lastOutput()'],['../classctrl_1_1GainScheduledController.html#a6f5d15987d686ceb2a0cf73211bcb119',1,'ctrl::GainScheduledController::lastOutput()'],['../classctrl_1_1FuzzyPID.html#aa53872025342ddfbc46e165b3e50fb57',1,'ctrl::FuzzyPID::lastOutput()'],['../classctrl_1_1FuzzyPD.html#a2d4fbca77923817e6136b4469ef430cb',1,'ctrl::FuzzyPD::lastOutput()'],['../classctrl_1_1FeedbackLinearisationController.html#a709fa8bdd183a25e0802dc098b255c57',1,'ctrl::FeedbackLinearisationController::lastOutput()'],['../classctrl_1_1DiscretePID.html#a2181cd169d2691a6d0be718e907a8306',1,'ctrl::DiscretePID::lastOutput()'],['../classctrl_1_1SimActuator.html#ad98fca771aaf43ba231720dff8bbeb53',1,'ctrl::SimActuator::lastOutput()']]],
  ['lastqpconverged_3',['lastqpconverged',['../classctrl_1_1DiscreteMPC.html#a4f704afde269d8b5f873a9adb6d2b1a2',1,'ctrl::DiscreteMPC::lastQPConverged()'],['../classctrl_1_1GeneralizedPredictiveController.html#a02c58aa49467163557ddc162333d067e',1,'ctrl::GeneralizedPredictiveController::lastQPConverged()']]],
  ['lastqpiters_4',['lastqpiters',['../classctrl_1_1DiscreteMPC.html#aa4c1215570b8434108bb00ab5aacb741',1,'ctrl::DiscreteMPC::lastQPIters()'],['../classctrl_1_1GeneralizedPredictiveController.html#aad7359afa8988f1de19236714b3a381f',1,'ctrl::GeneralizedPredictiveController::lastQPIters()'],['../classctrl_1_1MovingHorizonEstimator.html#a3169e53700ba2e8896f39f02283d9e4d',1,'ctrl::MovingHorizonEstimator::lastQPIters()']]],
  ['lastvalidreading_5',['lastValidReading',['../classctrl_1_1SafeSensor.html#ae10704d23bbb34984d1c14eb438e2a16',1,'ctrl::SafeSensor']]],
  ['latest_6',['latest',['../classctrl_1_1AtomicParamBuffer.html#a12b5b74ba394c034f1ea7a461140cb87',1,'ctrl::AtomicParamBuffer']]],
  ['layer_7',['5.4 Tuning Layer',['../md_docs_2DOCUMENTATION.html#autotoc_md105',1,'']]],
  ['layout_8',['Repository Layout',['../index.html#autotoc_md11',1,'']]],
  ['layout_20top_20level_9',['1.3 Repository Layout (Top Level)',['../md_docs_2DOCUMENTATION.html#autotoc_md32',1,'']]],
  ['ldlt_20failure_10',['MPC Infeasibility / LDLT Failure',['../md_docs_2DEPLOYMENT.html#autotoc_md166',1,'']]],
  ['leadlag_11',['LeadLag',['../namespacectrl.html#ae9f75df6083768f99f318568d9b9038aa7cacc882b6fbe96bad6aa3c3a0ea6677',1,'ctrl']]],
  ['leadlagparams_12',['LeadLagParams',['../structctrl_1_1LeadLagParams.html',1,'ctrl']]],
  ['leadlagtuneresult_13',['LeadLagTuneResult',['../structctrl_1_1LeadLagTuneResult.html',1,'ctrl']]],
  ['level_14',['1.3 Repository Layout (Top Level)',['../md_docs_2DOCUMENTATION.html#autotoc_md32',1,'']]],
  ['lib_20atomicparambuffer_20h_20atomicparambuffer_20h_20a_15',['&lt;tt&gt;AtomicParamBuffer&lt;Params&gt;&lt;/tt&gt; (&lt;a href=&quot;lib/AtomicParamBuffer.h&quot; &gt;AtomicParamBuffer.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md122',1,'']]],
  ['lib_20balancedtruncation_20h_20balancedtruncation_20h_20a_16',['&lt;tt&gt;BalancedTruncation&lt;/tt&gt; (&lt;a href=&quot;lib/BalancedTruncation.h&quot; &gt;BalancedTruncation.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md101',1,'']]],
  ['lib_20controllerstack_20h_20controllerstack_20h_20a_17',['&lt;tt&gt;ControllerStack&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerStack.h&quot; &gt;ControllerStack.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md115',1,'']]],
  ['lib_20controllertraits_20h_20controllertraits_20h_20a_18',['&lt;tt&gt;ControllerTraits&lt;C&gt;&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerTraits.h&quot; &gt;ControllerTraits.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md112',1,'']]],
  ['lib_20controllertuner_20h_20controllertuner_20h_20a_19',['&lt;tt&gt;RelayAutoTuner&lt;/tt&gt; (&lt;a href=&quot;lib/ControllerTuner.h&quot; &gt;ControllerTuner.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md106',1,'']]],
  ['lib_20discreteadrc_20h_20discreteadrc_20h_20a_20',['&lt;tt&gt;DiscreteADRC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteADRC.h&quot; &gt;DiscreteADRC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md74',1,'']]],
  ['lib_20discretehinf_20h_20discretehinf_20h_20a_21',['&lt;tt&gt;DiscreteHinf&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteHinf.h&quot; &gt;DiscreteHinf.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md81',1,'']]],
  ['lib_20discreteleadlag_20h_20discreteleadlag_20h_20a_22',['&lt;tt&gt;DiscreteLeadLag&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLeadLag.h&quot; &gt;DiscreteLeadLag.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md75',1,'']]],
  ['lib_20discretelqg_20h_20discretelqg_20h_20a_23',['&lt;tt&gt;DiscreteLQG&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLQG.h&quot; &gt;DiscreteLQG.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md72',1,'']]],
  ['lib_20discretelqr_20h_20discretelqr_20h_20a_24',['&lt;tt&gt;DiscreteLQR&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteLQR.h&quot; &gt;DiscreteLQR.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md70',1,'']]],
  ['lib_20discretempc_20h_20discretempc_20h_20a_25',['&lt;tt&gt;DiscreteMPC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteMPC.h&quot; &gt;DiscreteMPC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md71',1,'']]],
  ['lib_20discretepid_20h_20discretepid_20h_20a_26',['&lt;tt&gt;DiscretePID&lt;/tt&gt; (&lt;a href=&quot;lib/DiscretePID.h&quot; &gt;DiscretePID.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md69',1,'']]],
  ['lib_20discretesmc_20h_20discretesmc_20h_20a_27',['&lt;tt&gt;DiscreteSMC&lt;/tt&gt; (&lt;a href=&quot;lib/DiscreteSMC.h&quot; &gt;DiscreteSMC.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md73',1,'']]],
  ['lib_20extendedkalmanfilter_20h_20extendedkalmanfilter_20h_20a_28',['&lt;tt&gt;ExtendedKalmanFilter&lt;/tt&gt; (&lt;a href=&quot;lib/ExtendedKalmanFilter.h&quot; &gt;ExtendedKalmanFilter.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md92',1,'']]],
  ['lib_20extremumseeker_20h_20extremumseeker_20h_20a_29',['&lt;tt&gt;ExtremumSeeker&lt;/tt&gt; (&lt;a href=&quot;lib/ExtremumSeeker.h&quot; &gt;ExtremumSeeker.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md77',1,'']]],
  ['lib_20features_20h_20features_20h_20a_30',['&lt;tt&gt;std::unordered_map&lt;std::string, bool&gt; ctrl::features()&lt;/tt&gt; (&lt;a href=&quot;lib/Features.h&quot; &gt;Features.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md65',1,'']]],
  ['lib_20feedbacklinearisation_20h_20feedbacklinearisation_20h_20a_31',['&lt;tt&gt;FeedbackLinearisationController&lt;/tt&gt; (&lt;a href=&quot;lib/FeedbackLinearisation.h&quot; &gt;FeedbackLinearisation.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md98',1,'']]],
  ['lib_20feedforwardcontroller_20h_20feedforwardcontroller_20h_20a_32',['&lt;tt&gt;FeedforwardController&lt;/tt&gt; (&lt;a href=&quot;lib/FeedforwardController.h&quot; &gt;FeedforwardController.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md79',1,'']]],
  ['lib_20fopdtidentifier_20h_20fopdtidentifier_20h_20a_33',['&lt;tt&gt;FOPDTIdentifier&lt;/tt&gt; (&lt;a href=&quot;lib/FOPDTIdentifier.h&quot; &gt;FOPDTIdentifier.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md95',1,'']]],
  ['lib_20fuzzylogic_20h_20fuzzylogic_20h_20a_34',['Fuzzy Logic Module (&lt;a href=&quot;lib/FuzzyLogic.h&quot; &gt;FuzzyLogic.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md82',1,'']]],
  ['lib_20generalizedpredictivecontrol_20h_20generalizedpredictivecontrol_20h_20a_35',['&lt;tt&gt;GeneralizedPredictiveController&lt;/tt&gt; (&lt;a href=&quot;lib/GeneralizedPredictiveControl.h&quot; &gt;GeneralizedPredictiveControl.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md80',1,'']]],
  ['lib_20hal_20hal_20h_20lib_20hal_20hal_20h_20a_36',['HAL (&lt;a href=&quot;lib/hal/HAL.h&quot; &gt;lib/hal/HAL.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md123',1,'']]],
  ['lib_20icontroller_20h_20icontroller_20h_20a_37',['&lt;tt&gt;IController&lt;/tt&gt; (&lt;a href=&quot;lib/IController.h&quot; &gt;IController.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md66',1,'']]],
  ['lib_20kalmanfilter_20h_20kalmanfilter_20h_20a_38',['&lt;tt&gt;KalmanFilter&lt;/tt&gt; (&lt;a href=&quot;lib/KalmanFilter.h&quot; &gt;KalmanFilter.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md91',1,'']]],
  ['lib_20linearisationhelper_20h_20linearisationhelper_20h_20a_39',['&lt;tt&gt;LinearisationHelper&lt;/tt&gt; (&lt;a href=&quot;lib/LinearisationHelper.h&quot; &gt;LinearisationHelper.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md100',1,'']]],
  ['lib_20metricsanalyzer_20h_20metricsanalyzer_20h_20a_40',['&lt;tt&gt;MetricsAnalyzer&lt;/tt&gt; (&lt;a href=&quot;lib/MetricsAnalyzer.h&quot; &gt;MetricsAnalyzer.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md118',1,'']]],
  ['lib_20movinghorizonestimator_20h_20movinghorizonestimator_20h_20a_41',['&lt;tt&gt;MovingHorizonEstimator&lt;/tt&gt; (&lt;a href=&quot;lib/MovingHorizonEstimator.h&quot; &gt;MovingHorizonEstimator.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md94',1,'']]],
  ['lib_20mraccontroller_20h_20mraccontroller_20h_20a_42',['&lt;tt&gt;MRACController&lt;/tt&gt; (&lt;a href=&quot;lib/MRACController.h&quot; &gt;MRACController.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md97',1,'']]],
  ['lib_20plantmodel_20h_20plantmodel_20h_20a_43',['5.1 Core Types (&lt;a href=&quot;lib/PlantModel.h&quot; &gt;PlantModel.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md59',1,'']]],
  ['lib_20recursiveleastsquares_20h_20recursiveleastsquares_20h_20a_44',['&lt;tt&gt;RecursiveLeastSquares&lt;/tt&gt; (&lt;a href=&quot;lib/RecursiveLeastSquares.h&quot; &gt;RecursiveLeastSquares.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md99',1,'']]],
  ['lib_20repetitivecontroller_20h_20repetitivecontroller_20h_20a_45',['&lt;tt&gt;RepetitiveController&lt;/tt&gt; (&lt;a href=&quot;lib/RepetitiveController.h&quot; &gt;RepetitiveController.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md78',1,'']]],
  ['lib_20smithpredictor_20h_20smithpredictor_20h_20a_46',['&lt;tt&gt;SmithPredictor&lt;/tt&gt; (&lt;a href=&quot;lib/SmithPredictor.h&quot; &gt;SmithPredictor.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md76',1,'']]],
  ['lib_20sopdtidentifier_20h_20sopdtidentifier_20h_20a_47',['&lt;tt&gt;SOPDTIdentifier&lt;/tt&gt; (&lt;a href=&quot;lib/SOPDTIdentifier.h&quot; &gt;SOPDTIdentifier.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md96',1,'']]],
  ['lib_20subspaceid_20h_20subspaceid_20h_20a_48',['&lt;tt&gt;SubspaceID&lt;/tt&gt; (&lt;a href=&quot;lib/SubspaceID.h&quot; &gt;SubspaceID.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md103',1,'']]],
  ['lib_20systemanalysis_20h_20systemanalysis_20h_20a_49',['&lt;tt&gt;SystemAnalysis&lt;/tt&gt; (&lt;a href=&quot;lib/SystemAnalysis.h&quot; &gt;SystemAnalysis.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md119',1,'']]],
  ['lib_20tt_50',['3.1 Library (&lt;tt&gt;lib/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md42',1,'']]],
  ['lib_20tunersuite_20h_20tunersuite_20h_20a_51',['&lt;tt&gt;TunerSuite&lt;/tt&gt; (&lt;a href=&quot;lib/TunerSuite.h&quot; &gt;TunerSuite.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md111',1,'']]],
  ['lib_20unscentedkalmanfilter_20h_20unscentedkalmanfilter_20h_20a_52',['&lt;tt&gt;UnscentedKalmanFilter&lt;/tt&gt; (&lt;a href=&quot;lib/UnscentedKalmanFilter.h&quot; &gt;UnscentedKalmanFilter.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md93',1,'']]],
  ['lib_20zerophasetrackingfilter_20h_20zerophasetrackingfilter_20h_20a_53',['&lt;tt&gt;ZeroPhaseTrackingFilter&lt;/tt&gt; (&lt;a href=&quot;lib/ZeroPhaseTrackingFilter.h&quot; &gt;ZeroPhaseTrackingFilter.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md102',1,'']]],
  ['library_54',['2.3 Linking Against the Library',['../md_docs_2DOCUMENTATION.html#autotoc_md37',1,'']]],
  ['library_20tt_20lib_20tt_55',['3.1 Library (&lt;tt&gt;lib/&lt;/tt&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md42',1,'']]],
  ['linearblend_56',['LinearBlend',['../namespacectrl.html#ac4b116227149e74ff44404995b9b5f9fa6e14db3e35ac130427b397988bfd00df',1,'ctrl']]],
  ['linearisation_20adaptive_20mpc_57',['4.4 MPC with Online Re-Linearisation (Adaptive MPC)',['../md_docs_2DOCUMENTATION.html#autotoc_md53',1,'']]],
  ['linearisationhelper_20tt_20a_20href_20lib_20linearisationhelper_20h_20linearisationhelper_20h_20a_58',['&lt;tt&gt;LinearisationHelper&lt;/tt&gt; (&lt;a href=&quot;lib/LinearisationHelper.h&quot; &gt;LinearisationHelper.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md100',1,'']]],
  ['linearisationhelper_2ecpp_59',['LinearisationHelper.cpp',['../LinearisationHelper_8cpp.html',1,'']]],
  ['linearisationhelper_2eh_60',['LinearisationHelper.h',['../LinearisationHelper_8h.html',1,'']]],
  ['lineariseatpoint_61',['lineariseatpoint',['../namespacectrl.html#ac2fc008e90dd6887e79f686a96c5ddc3',1,'ctrl::lineariseAtPoint(const StateFunc &amp;f_continuous, const MeasFunc &amp;h, const Eigen::VectorXd &amp;x0, const Eigen::VectorXd &amp;u0, double Ts, double eps_scale=1e-4)'],['../namespacectrl.html#aaae0366d018b76c601905f757643273d',1,'ctrl::lineariseAtPoint(const StateFunc &amp;f_continuous, const Eigen::VectorXd &amp;x0, const Eigen::VectorXd &amp;u0, double Ts, double eps_scale=1e-4)']]],
  ['linearmodelcluster_2eh_62',['LinearModelCluster.h',['../LinearModelCluster_8h.html',1,'']]],
  ['linguisticterm_63',['LinguisticTerm',['../structctrl_1_1LinguisticTerm.html',1,'ctrl']]],
  ['linguisticvariable_64',['LinguisticVariable',['../structctrl_1_1LinguisticVariable.html',1,'ctrl']]],
  ['linguisticvariable_20tt_65',['&lt;tt&gt;LinguisticVariable&lt;/tt&gt;',['../md_docs_2DOCUMENTATION.html#autotoc_md84',1,'']]],
  ['linking_20against_20the_20library_66',['2.3 Linking Against the Library',['../md_docs_2DOCUMENTATION.html#autotoc_md37',1,'']]],
  ['lo_67',['lo',['../structctrl_1_1LinguisticVariable.html#aee24abd6bc5fe725390a8205365cecfc',1,'ctrl::LinguisticVariable']]],
  ['lock_20free_20parameter_20updates_68',['AtomicParamBuffer - Lock-Free Parameter Updates',['../md_docs_2DEPLOYMENT.html#autotoc_md159',1,'']]],
  ['logic_20module_20a_20href_20lib_20fuzzylogic_20h_20fuzzylogic_20h_20a_69',['Fuzzy Logic Module (&lt;a href=&quot;lib/FuzzyLogic.h&quot; &gt;FuzzyLogic.h&lt;/a&gt;)',['../md_docs_2DOCUMENTATION.html#autotoc_md82',1,'']]],
  ['loop_20example_20siso_20pid_70',['4.1 Minimum Closed-Loop Example (SISO PID)',['../md_docs_2DOCUMENTATION.html#autotoc_md50',1,'']]],
  ['loopshaping_71',['loopShaping',['../classctrl_1_1TunerSuite.html#a68241e3f0b3f6f4a023ab58ea82bf3f2',1,'ctrl::TunerSuite']]],
  ['loopshapingtuner_72',['LoopShapingTuner',['../classctrl_1_1LoopShapingTuner.html',1,'ctrl']]],
  ['loopshapingtuner_20tt_20tt_20kalmanweighttuner_20tt_73',['&lt;tt&gt;ZieglerNicholsTuner&lt;/tt&gt;, &lt;tt&gt;CohenCoonTuner&lt;/tt&gt;, &lt;tt&gt;LoopShapingTuner&lt;/tt&gt;, &lt;tt&gt;KalmanWeightTuner&lt;/tt&gt;',['../md_docs_2DOCUMENTATION.html#autotoc_md110',1,'']]],
  ['lpfcutoff_74',['lpfCutoff',['../structctrl_1_1ExtremumSeekerParams.html#a48488068e06ea9a3555f45bf13a52cc1',1,'ctrl::ExtremumSeekerParams']]],
  ['lpvmodel_75',['LPVModel',['../structctrl_1_1LPVModel.html',1,'ctrl']]],
  ['lpvsystemid_2ecpp_76',['LPVSystemID.cpp',['../LPVSystemID_8cpp.html',1,'']]],
  ['lpvsystemid_2eh_77',['LPVSystemID.h',['../LPVSystemID_8h.html',1,'']]],
  ['lqg_78',['LQG',['../namespacectrl.html#ae9f75df6083768f99f318568d9b9038aa21d16cd097fc5e73bbaf35a33f632f74',1,'ctrl']]],
  ['lqg_20output_20feedback_79',['4.3 LQR + Kalman = LQG (Output Feedback)',['../md_docs_2DOCUMENTATION.html#autotoc_md52',1,'']]],
  ['lqr_80',['LQR',['../namespacectrl.html#ae9f75df6083768f99f318568d9b9038aaa6e6a19e8d19a6641a626a0bf2a39919',1,'ctrl']]],
  ['lqr_20kalman_20lqg_20output_20feedback_81',['4.3 LQR + Kalman = LQG (Output Feedback)',['../md_docs_2DOCUMENTATION.html#autotoc_md52',1,'']]],
  ['lqradapter_82',['lqradapter',['../classctrl_1_1LQRAdapter.html',1,'ctrl::LQRAdapter'],['../classctrl_1_1LQRAdapter.html#a83bc714547dbe21e26b898e60bada666',1,'ctrl::LQRAdapter::LQRAdapter()']]],
  ['lqrparams_83',['LQRParams',['../structctrl_1_1LQRParams.html',1,'ctrl']]],
  ['lqrtuneresult_84',['LQRTuneResult',['../structctrl_1_1LQRTuneResult.html',1,'ctrl']]],
  ['lqrweighttuner_85',['LQRWeightTuner',['../classctrl_1_1LQRWeightTuner.html',1,'ctrl']]],
  ['lqrweighttuner_20tt_86',['&lt;tt&gt;LQRWeightTuner&lt;/tt&gt;',['../md_docs_2DOCUMENTATION.html#autotoc_md108',1,'']]],
  ['ltsingleton_87',['ltSingleton',['../namespacectrl.html#a8f1dad886251652b6661dd678241730e',1,'ctrl']]]
];
