// ============================================================
//  ex23_fuzzy_pd_temperature.cpp
//  Application: HVAC zone temperature control.
//
//  Plant: second-order thermal model
//    G(s) = 1 / (200s + 1)(60s + 1)   [^\circC / kW]
//  Discretised at Ts = 5 s (ZOH).
//
//  Compares FuzzyPD vs DiscretePID on:
//    - Reference step 20^\circC -> 22^\circC at t = 0
//    - Load disturbance (window opened) -0.5 kW at t = 300 s
//
//  Data generated by Python script ex23_gen.py.
//  Output columns: t, ref, y_fuzzy, u_fuzzy, y_pid, u_pid, disturbance
// ============================================================
#include "ControllerToolbox.h"
#include <fstream>
#include <iomanip>
#include <iostream>

int main()
{
    const double Ts  = 5.0;    // 5-second sample (HVAC typical)
    const double ref = 22.0;   // ^\circC setpoint

    // -- Plant: G(s) = 1/((200s+1)(60s+1)) discretised by ZOH ----------------
    // Continuous SS:  [T_wall; T_air]
    //   A_c = [-1/200  0; 1/60  -1/60],  B_c = [1/200; 0],  C = [0 1]
    Eigen::Matrix2d Ac; Ac << -1.0/200, 0, 1.0/60, -1.0/60;
    Eigen::Vector2d Bc; Bc << 1.0/200, 0;
    Eigen::RowVector2d Cc; Cc << 0, 1;
    Eigen::MatrixXd Dc(1,1); Dc << 0;

    ctrl::StateSpace plant_c(Ac, Bc, Cc, Dc, 0.0);
    ctrl::StateSpace plant = ctrl::c2d(plant_c, Ts, ctrl::C2dMethod::ZOH);

    // -- FuzzyPD controller ----------------------------------------------------
    // e_scale  = 2^\circC  (full deflection = +/-2^\circC error)
    // de_scale = 0.2^\circC/s
    // u_scale  = 3 kW  (max heater output)
    ctrl::FuzzyPDParams fp;
    fp.e_scale  = 2.0;
    fp.de_scale = 0.2;
    fp.u_scale  = 3.0;
    fp.uMin     = 0.0;    // heater: cannot cool
    fp.uMax     = 3.0;

    ctrl::FuzzyPD fuzzy(fp, Ts);

    // -- Reference PID ---------------------------------------------------------
    // Tuned via Bryson/IMC for the same plant (tau_c = 80 s)
    ctrl::PIDParams pp;
    pp.Kp  = 1.8;
    pp.Ki  = 0.006;
    pp.Kd  = 40.0;
    pp.N   = 5.0;
    pp.Kb  = 1.0;
    pp.uMin = 0.0;
    pp.uMax = 3.0;
    ctrl::DiscretePID pid(pp, Ts);

    // -- Simulation ------------------------------------------------------------
    const int N = 200;   // 1000 s total
    double y_f = 20.0, y_p = 20.0;
    Eigen::VectorXd xf = Eigen::VectorXd::Zero(plant.stateSize());
    Eigen::VectorXd xp = Eigen::VectorXd::Zero(plant.stateSize());
    // Warm-start state to initial temperature of 20^\circC
    // (output = C*x = x(1) for this SS, so x1 = 20 satisfies y=20 at steady state)
    xf(1) = 20.0 * (1.0 + 1.0/200 * 60);  // approximate steady state
    xp    = xf;

    std::ofstream csv("data/ex23_fuzzy_temperature.csv");
    csv << "t,ref,y_fuzzy,u_fuzzy,y_pid,u_pid,disturbance\n";
    csv << std::fixed << std::setprecision(4);

    std::cout << "=== FuzzyPD vs PID - HVAC Temperature Control ===\n";
    std::cout << "  k     t[s]   ref    y_fuzzy  u_fuzzy   y_pid   u_pid   dist\n";
    std::cout << std::string(74, '-') << "\n";

    for (int k = 0; k < N; ++k) {
        double t    = k * Ts;
        double dist = (t >= 300.0) ? -0.5 : 0.0;   // window-open disturbance

        // FuzzyPD
        double uf = fuzzy.compute(ref - y_f);
        uf = std::clamp(uf + dist, 0.0, 3.0);

        // PID
        double up = pid.compute(ref - y_p);
        up = std::clamp(up + dist, 0.0, 3.0);

        Eigen::VectorXd uvf(1); uvf << uf;
        Eigen::VectorXd uvp(1); uvp << up;

        y_f = ctrl::ssStep(plant, xf, uvf)(0) + 20.0 * std::exp(-t / 200.0) * 0.0;
        y_p = ctrl::ssStep(plant, xp, uvp)(0);
        // Note: initial offset handled by warm-started x vector above.
        // ssStep returns temperature relative to zero; actual output is y_f directly.

        csv << t << "," << ref << "," << y_f << "," << uf << ","
            << y_p << "," << up << "," << (dist != 0 ? 1 : 0) << "\n";

        if (k % 20 == 0)
            std::cout << std::setw(4) << k
                      << std::setw(8)  << t
                      << std::setw(6)  << ref
                      << std::setw(10) << y_f
                      << std::setw(9)  << uf
                      << std::setw(9)  << y_p
                      << std::setw(8)  << up
                      << std::setw(7)  << dist << "\n";
    }

    std::cout << "\nResults saved to data/ex23_fuzzy_temperature.csv\n";
    return 0;
}
