"""
Detect and report the status of every case study under case-study/.

Language detection (in priority order):
  1. sim/main.py exists → Python
     sim/src/main.cpp exists → C++
  2. sim/src/ directory exists → C++ (depth heuristic)
     sim/ directory exists → Python
  3. Count source file extensions across the whole study tree.

Status detection:
  Complete  — has sim/, logs/ with CSVs, config/, AND a .html report
  On-going  — has sim/, logs/ with CSVs, and config/
  Incomplete — has at least one PDF and a README.md (spec only)
  Not started — default

Output: docs/case_study_status.md  (Markdown table)
"""
from __future__ import annotations

import os
import pathlib

ROOT = pathlib.Path("case-study")
DOCS_DIR = pathlib.Path("docs")

CPP_EXTENSION = {'.cpp', '.cc', '.cxx', '.c', '.h', '.hpp', '.hh', '.hxx', '.ixx', '.cppm', '.tpp', '.ipp'}
PYTHON_EXTENSION = {'.py', '.pyc', '.ipynb', '.toml', '.so', '.pyd'}


# ── Language detection ────────────────────────────────────────────────────────

def detect_language(case_study_path: pathlib.Path) -> str:
    # Step 1: check for main files
    if (case_study_path / "sim" / "main.py").exists():
        return "Python"
    if (case_study_path / "sim" / "src" / "main.cpp").exists():
        return "C++"

    # Step 2: depth heuristic on sim/
    sim = case_study_path / "sim"
    if sim.exists():
        if (sim / "src").exists():
            return "C++"
        return "Python"

    # Step 3: count source file extensions across the whole study
    cpp_count = 0
    python_count = 0
    for f in case_study_path.rglob("*"):
        if f.is_file():
            ext = f.suffix.lower()
            if ext in CPP_EXTENSION:
                cpp_count += 1
            elif ext in PYTHON_EXTENSION:
                python_count += 1

    if cpp_count > 0 and python_count == 0:
        return "C++"
    if python_count > 0 and cpp_count == 0:
        return "Python"
    if cpp_count > 0 and python_count > 0:
        return "mixed"
    return "undetermined"


# ── Status detection ──────────────────────────────────────────────────────────

def _has_config(path: pathlib.Path) -> bool:
    for candidate in ("config", "configs", "sim/config", "sim/configs"):
        d = path / candidate
        if d.exists() and d.is_dir():
            return True
    return False


def _has_logs(path: pathlib.Path) -> bool:
    logs = path / "logs"
    if not logs.exists():
        return False
    return any(f.suffix == ".csv" for f in logs.iterdir() if f.is_file())


def _has_sim(path: pathlib.Path) -> bool:
    sim = path / "sim"
    if not sim.exists():
        return False
    return any(True for f in sim.rglob("main.*") if f.is_file())


def detect_status(case_study_path: pathlib.Path) -> str:
    has_sim    = _has_sim(case_study_path)
    has_logs   = _has_logs(case_study_path)
    has_config = _has_config(case_study_path)
    has_report = any(case_study_path.rglob("*.html"))
    has_pdf    = any(True for f in case_study_path.iterdir()
                     if f.is_file() and f.suffix.lower() == ".pdf")
    has_readme = (case_study_path / "README.md").exists()

    if has_sim and has_logs and has_config and has_report:
        return "Complete"
    if has_sim and has_logs and has_config:
        return "On-going"
    if has_pdf and has_readme:
        return "Incomplete"
    if has_pdf or has_readme:
        return "Incomplete"
    return "Not started"


# ── Link helpers ──────────────────────────────────────────────────────────────

def _rel_from_docs(path: pathlib.Path) -> str:
    return os.path.relpath(path, DOCS_DIR).replace(os.sep, "/")


def find_pdf_link(case_study_path: pathlib.Path) -> str:
    for pdf in sorted(case_study_path.glob("*.pdf")):
        return f"[{pdf.name}]({_rel_from_docs(pdf)})"
    return "—"


def find_readme_link(case_study_path: pathlib.Path) -> str:
    readme = case_study_path / "README.md"
    if readme.exists():
        return f"[README]({_rel_from_docs(readme)})"
    return "—"


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    entries = []
    for name in sorted(ROOT.iterdir(), key=lambda p: p.name.lower()):
        if not name.is_dir() or name.name == "__pycache__":
            continue
        language  = detect_language(name)
        status    = detect_status(name)
        reference = find_pdf_link(name)
        link      = find_readme_link(name)
        entries.append((name.name, language, reference, status, link))

    # Build markdown table
    header = (
        "# Case Study Status\n\n"
        "<!-- Auto-generated by tools/case_study_tracker.py — do not edit manually -->\n\n"
        "| Case Study Name | Language | Reference | Status | Link |\n"
        "|---|---|---|---|---|\n"
    )
    rows = "\n".join(
        f"| {name} | {lang} | {ref} | {status} | {lnk} |"
        for name, lang, ref, status, lnk in entries
    )

    out_path = DOCS_DIR / "case_study_status.md"
    out_path.write_text(header + rows + "\n", encoding="utf-8")
    print(f"Written {len(entries)} entries → {out_path}")

    # Summary counts
    from collections import Counter
    status_counts = Counter(e[3] for e in entries)
    lang_counts   = Counter(e[1] for e in entries)
    print(f"\nStatus:   {dict(status_counts)}")
    print(f"Language: {dict(lang_counts)}")


if __name__ == "__main__":
    main()
